server:
  port: 4004

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
              ## REST CLIENT -> http://localhost:4004/api/patients
              ## API GATEWAY -> http://patient-service:4000/patients
            - id: patient-service-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api/patients/**
              filters:
                ## This filter removes the first segment of the path, so that the request to http://localhost:4004/api/patients/1 will be forwarded to http://patient-service:4000/patients/1 instead of http://patient-service:4000/api/patients/1
                - StripPrefix=1

              ## REST-CLIENT -> http://localhost:4004/api-docs/patients
              ## API GATEWAY -> http://patient-service:4000/v3/api-docs
            - id: api-docs-patient-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api-docs/patients
              filters:
                - RewritePath=/api-docs/patients, /v3/api-docs

            - id: billing-service-route
              uri: http://billing-service:4001
              predicates:
                - Path=/api/billing/**
              filters:
                - StripPrefix=1


