### POST a new patient to the patient service API.
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe kafka-demo",
  "email": "test_billing_account456@gmail.com",
  "address": "123 Main St, Anytown, USA",
  "dateOfBirth": "1990-01-01",
  "registeredDate": "2024-06-01"
}
###