### update patient information
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174001
Content-Type: application/json

{
  "name": "Lloyd",
  "email": "test_updated@gmail.com",
  "address": "123 Main St, Anytown, USA",
  "dateOfBirth": "1990-01-01"
}
###