spring.application.name=patient_service

# UNCOMMENT TO USE IN LOCAL DATABASE OUTSIDE OF DOCKER
#spring.datasource.url=jdbc:postgresql://localhost:5432/
#spring.datasource.username=postgres
#spring.datasource.password=Vidhanshu@37
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=always

server.port=4000
logging.level.root=info