spring.application.name=patient_service

# UNCOMMENT TO USE IN LOCAL DATABASE OUTSIDE OF DOCKER
#spring.datasource.url=jdbc:postgresql://localhost:5432/
#spring.datasource.username=postgres
#spring.datasource.password=Vidhanshu@37
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=always

spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer

spring.kafka.consumer.group-id=patient-group
spring.kafka.consumer.auto-offset-reset=earliest

server.port=4000
logging.level.root=info